name: Deploy Site and Docs to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'apps/site/**'
      - 'apps/docs/**'
      - '.github/workflows/deploy-combined.yml'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    name: Deploy Site and Docs to GitHub Pages
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install root dependencies
        run: npm i

      - name: Install site dependencies
        working-directory: apps/site
        run: npm i

      - name: Install docs dependencies
        working-directory: apps/docs
        run: npm i
      
      - name: Build site for GitHub Pages
        working-directory: apps/site
        run: npm run build
        env:
          NODE_ENV: production
          GITHUB_PAGES: true
          GITHUB_REPOSITORY: ${{ github.repository }}

      - name: Build docs website
        working-directory: apps/docs
        run: npm run build

      - name: Prepare combined deployment
        run: |
          # Create deployment directory
          mkdir -p deployment
          
          # Copy site to root
          cp -r apps/site/out/* deployment/
          
          # Copy docs to /docs subdirectory
          mkdir -p deployment/docs
          cp -r apps/docs/build/* deployment/docs/
          
          # Ensure .nojekyll exists
          touch deployment/.nojekyll

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: deployment

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 