name: Deploy Site to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'apps/site/**'
      - '.github/workflows/deploy-site.yml'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    name: Deploy Site to GitHub Pages
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: 'apps/site/package-lock.json'

      - name: Install root dependencies
        run: npm ci

      - name: Install site dependencies
        working-directory: apps/site
        run: npm ci
      
      - name: Build site for GitHub Pages
        working-directory: apps/site
        run: npm run build:github
        env:
          NODE_ENV: production
          GITHUB_PAGES: true
          GITHUB_REPOSITORY: ${{ github.repository }}

      - name: Add .nojekyll file
        run: touch apps/site/out/.nojekyll

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: apps/site/out

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 